---

# Copyright 2016 David Stanek <dstanek@dstanek.com>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Download Shibboleth RPM repo for CentOS/RedHat 7
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'
  get_url:
    url: http://download.opensuse.org/repositories/security://shibboleth/CentOS_7/security:shibboleth.repo
    dest: /etc/yum.repos.d/shibboleth.repo

- name: Install Shibboleth
  package:
    name: "{{ keystone_sp_shib_pkg }}"
    state: present
  register: install_shib
  notify:
    - restart apache
